apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: {{ .Values.replicacount }}
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-sample-app
        image: {{ .Values.sourceimage.repository }}:{{ .Values.sourceimage.tag }} 
        imagePullPolicy: {{ .Values.sourceimage.pullPolicy }}
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: myregcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
  name: nginx-svc
  namespace: test-env
spec:
  type: ClusterIP 
  selector:
    app: nginx-app
  ports:
    - name: http
      port: 80
#      nodePort: 32321
#      targetPort: http
#      protocol: TCP

